DROP TABLE IF EXISTS users, categories,locations,events, requests, compilations, compilations_events, comments  CASCADE;

CREATE TABLE IF NOT EXISTS users(
    user_id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    user_name	        VARCHAR(250) NOT NULL,
    user_email          VARCHAR(254) NOT NULL UNIQUE

    );

CREATE TABLE IF NOT EXISTS categories(
    category_id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    category_name       VARCHAR(50) NOT NULL UNIQUE

    );

CREATE TABLE IF NOT EXISTS locations(
    location_id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    location_lat        FLOAT,
    location_lon        FLOAT

    );

CREATE TABLE IF NOT EXISTS events(
    event_id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    event_annotation    VARCHAR(2000) NOT NULL,
    event_category_id   BIGINT NOT NULL REFERENCES categories(category_id),
    event_created_on    TIMESTAMP,
    event_description   VARCHAR(7000) NOT NULL,
    event_date          TIMESTAMP NOT NULL,
    event_initiator_id  BIGINT REFERENCES users(user_id),
    event_location_id   BIGINT NOT NULL REFERENCES locations(location_id),
    event_paid          BOOLEAN,
    participant_limit   INTEGER,
    event_published_on  TIMESTAMP,
    request_moderation  BOOLEAN,
    event_state         VARCHAR(10)  NOT NULL,
    event_title         VARCHAR(120) NOT NULL,
    confirmed_requests  INTEGER

    );

CREATE TABLE IF NOT EXISTS requests(
    request_id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    requester_id        BIGINT REFERENCES users (user_id) ON DELETE CASCADE,
    event_id            BIGINT REFERENCES events (event_id) ON DELETE CASCADE,
    request_status      VARCHAR(30) NOT NULL,
    request_created     TIMESTAMP WITHOUT TIME ZONE NOT NULL

    );

CREATE TABLE IF NOT EXISTS compilations (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    title               VARCHAR(50) NOT NULL,
    pinned              BOOLEAN NOT NULL

    );

CREATE TABLE IF NOT EXISTS compilations_events (
	events_id           INTEGER REFERENCES events (event_id) ON DELETE CASCADE,
	compilation_id      INTEGER REFERENCES compilations (id) ON DELETE CASCADE,
	CONSTRAINT PK_EVENTS_COMPILATIONS PRIMARY KEY(events_id, compilation_id)

    );

CREATE TABLE IF NOT EXISTS comments (
    comment_id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    comment_text        VARCHAR(1500) NOT NULL,
    comment_event_id     BIGINT NOT NULL REFERENCES events(event_id),
    comment_author_id    BIGINT NOT NULL REFERENCES users(user_id),
    comment_created      TIMESTAMP WITHOUT TIME ZONE,
    comment_updated_on   TIMESTAMP WITHOUT TIME ZONE

    );